name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build build-essential llvm
      - run: pip3 install meson
      - run: CC=clang meson build
      - run: meson compile -C build